- id: doi:10.1371/journal.pcbi.1007128
  type: paper
  description: Lorem ipsum _dolor_ **sit amet**, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
  date: 2020-12-4
  image: https://journals.plos.org/ploscompbiol/article/figure/image?size=inline&id=info:doi/10.1371/journal.pcbi.1007128.g001&rev=2
  buttons:
    - type: manubot
      link: https://greenelab.github.io/meta-review/
    - type: source
      text: Manuscript Source
      link: https://github.com/greenelab/meta-review
    - type: website
      link: http://manubot.org/
  tags:
    - open science
    - collaboration
  repo: greenelab/meta-review

- id: doi:10.64898/2026.03.22.713509
  publisher: bioRxiv
  image: images/2026_rogers.png
  tags:
    - introgression
    - ancient DNA
    - genomics

- id: doi:10.1038/s41598-025-07399-3
  image: images/2025_beeby.jpeg
  tags:
    - microbiome
    - diet
    - ecology
    - lemurs

- id: doi:10.1111/mec.17600
  image: images/2024_mellor.jpg
  date: '2025-01-01'
  tags:
    - genomics
    - speciation
    - reptiles
    - adaptation

- id: doi:10.5281/zenodo.13728520
  remove: true

- id: doi:10.5281/zenodo.13728519
  remove: true

- id: doi:10.22541/au.172532972.22372724/v1
  remove: true

- id: doi:10.1093/gbe/evae210
  image: images/2023_brand.jpg
  tags:
    - genomics
    - speciation
    - chimpanzees and bonobos