- id: doi:10.1371/journal.pcbi.1007128
  type: paper
  description: Lorem ipsum _dolor_ **sit amet**, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
  date: 2020-12-4
  image: https://journals.plos.org/ploscompbiol/article/figure/image?size=inline&id=info:doi/10.1371/journal.pcbi.1007128.g001&rev=2
  buttons:
    - type: manubot
      link: https://greenelab.github.io/meta-review/
    - type: source
      text: Manuscript Source
      link: https://github.com/greenelab/meta-review
    - type: website
      link: http://manubot.org/
  tags:
    - open science
    - collaboration
  repo: greenelab/meta-review
  remove: true

- id: doi:10.64898/2026.03.22.713509
  publisher: bioRxiv
  image: images/2026_rogers.png
  tags:
    - introgression
    - ancient DNA
    - genomics

- id: doi:10.1038/s41598-025-07399-3
  image: images/2025_beeby.jpeg
  tags:
    - microbiome
    - diet
    - ecology
    - behavior
    - lemurs
    - primates

- id: doi:10.1111/mec.17600
  image: images/2024_mellor.jpg
  date: '2025-01-01'
  tags:
    - genomics
    - speciation
    - reptiles
    - adaptation
    - tortoises

- id: doi:10.5281/zenodo.13728520
  remove: true

- id: doi:10.5281/zenodo.13728519
  remove: true

- id: doi:10.22541/au.172532972.22372724/v1
  remove: true

- id: doi:10.1093/gbe/evae210
  image: images/2023_brand.jpg
  tags:
    - genomics
    - speciation
    - chimpanzees and bonobos

- id: doi:10.1093/gbe/evae018
  image: images/2024_webster.jpg
  tags:
    - genomics
    - reptiles
    - sex chromosomes

- id: doi:10.1371/journal.pone.0287609
  image: images/2021_cotter.png
  tags:
    - genomics
    - sex chromosomes

- id: doi:10.1101/2023.04.26.538436
  publisher: bioRxiv
  remove: true

- id: doi:10.1016/j.jaridenv.2023.105089
  image: images/2023_kollath.jpg
  tags:
    - microbiome
    - reptiles
    - tortoises
    - pathogens

- id: doi:10.1073/pnas.2200858119
  image: images/2022_brand.png
  tags:
    - genomics
    - chimpanzees and bonobos
    - introgression
    - primates
    - speciation

- id: doi:10.1101/2022.01.07.475438
  remove: true

- id: doi:10.1073/pnas.2116681119
  image: images/2021_byrne.jpg
  tags:
    - genomics
    - adaptation
    - primates

- id: doi:10.1101/2021.08.19.456368
  publisher: bioRxiv
  remove: true

- id: doi:10.1126/sciadv.abd2274
  image: images/2021_guevara.jpg
  tags:
    - genomics
    - adaptation
    - primates
    - lemurs
    - diet
    - ecology

- id: doi:10.1101/2021.01.31.429027
  publisher: bioRxiv
  remove: true

- id: doi:10.1111/1755-0998.13260
  date: '2021-01-01'
  image: images/2020_ozga.png
  tags:
    - genomics
    - methods
    - chimpanzees and bonobos
    - primate

- id: doi:10.1038/s41598-021-90409-x
  image: images/2020_lasisi.png
  tags:
    - methods
    - hair

- id: doi:10.1038/s41598-021-90170-1
  image: images/2021_phung.jpg
  tags:
    - genomics
    - cancer

- id: doi:10.1101/2020.12.14.422788
  publisher: bioRxiv
  image: images/2020_brand.png
  tags:
    - genomics
    - primates
    - adaptation
    - chimpanzees and bonobos
    - speciation

- id: doi:10.1101/2020.11.24.392191
  publisher: bioRxiv
  remove: true

- id: doi:10.1016/j.anbehav.2020.04.003
  image: images/2020_baden.jpg
  tags:
    - lemurs
    - fission-fusion
    - behavior
    - primates

- id: doi:10.1101/2020.02.18.955377
  publisher: bioRxiv
  remove: true

- id: doi:10.1093/gbe/evaa016
  image: images/2020_dolby.png
  tags:
    - genomics
    - tortoises
    - reptiles

- id: doi:10.3390/v12020143
  image: images/2020_orton.png
  tags:
    - tortoises
    - reptiles
    - microbiome
    - pathogens

- id: doi:10.1101/799825
  publisher: bioRxiv
  remove: true

- id: doi:10.1016/j.ympev.2020.106920
  image: images/2020_torosin_selection.jpg
  tags:
    - genomics
    - primates
    - adaptation
    - pathogens
    - sex chromosomes

- id: doi:10.1002/ajpa.24086
  image: images/2020_torosin_argentina.png
  tags:
    - genomics
    - primates
    - adaptation
    - pathogens
    - sex chromosomes

- id: doi:10.1101/725333
  publisher: bioRxiv
  remove: true

- id: doi:10.1101/708008
  publisher: bioRxiv
  remove: true

- id: doi:10.1093/gigascience/giz074
  image: images/xyalign_logo.png
  tags:
    - methods
    - genomics
    - sex chromosomes

- id: doi:10.5281/zenodo.2635885
  remove: true

- id: doi:10.1101/490839
  image: images/2018_webster_sifaka.png
  publisher: bioRxiv
  tags:
    - genomics
    - methods
    - primates
    - lemurs

- id: doi:10.1038/s41592-018-0046-7
  image: images/2018_bioconda.png
  tags:
    - methods
    - genomics

- id: doi:10.1101/346940
  publisher: bioRxiv
  remove: true

- id: doi:10.7287/peerj.preprints.3266v4
  image: images/2018_gagassizii_leander_photo.jpg
  tags:
    - genomics
    - reptiles
    - tortoises

- id: doi:10.7287/peerj.preprints.3266v3
  remove: true

- id: doi:10.1093/gbe/evw263
  image: images/2017_rupp.png
  date: '2017-01-01'
  tags:
    - genomics
    - sex chromosomes
    - reptiles

- id: doi:10.1016/j.gde.2016.08.002
  image: images/2016_webster.png
  tags:
    - review
    - genomics
    - sex chromosomes

- id: doi:10.1002/ajp.22507
  date: '2016-02-01'
  image: images/2016_baden.png
  tags:
    - fission-fusion
    - behavior
    - primates
    - lemurs

- title: Chimpanzees at Semliki ignore oil palms
  date: '2010-12-01'
  image: 2010_mcgrew.jpg
  tags:
    - primates
    - behavior
    - culture
    - chimpanzees and bonobos
    - diet
